substitutions:
  device_name: "smart-battery"
  node_name: "Smart Battery"
  node_id: smart_battery
  mac_address: a5:c2:37:00:f0:fc
  cell_volt_limit_min: "2.8" # Must be equal to BMS config setting
  cell_volt_limit_max: "3.388" # Must be equal to BMS config setting
  balancer_relay_pin: GPIO25
  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO22
  balancer_start_delta_mv: "20.0"
  balancer_stop_delta_mv: "10.0"
  balancer_min_work_time: 20min

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

packages:
  main: !include smart-battery/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include includes/common_system.yaml
  common_sensors: !include includes/common_sensors.yaml

logger:
  level: WARNING
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

sensor:
  - platform: template
    name: "Adjusted SoC"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery
    state_class: measurement
    update_interval: 10s
    lambda: |-
      return id(average_cell_voltage).state;
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 2.800 -> 0.0
          - 3.144 -> 10.0
          - 3.170 -> 20.0
          - 3.188 -> 30.0
          - 3.208 -> 40.0
          - 3.214 -> 50.0
          - 3.220 -> 60.0
          - 3.226 -> 70.0
          - 3.233 -> 80.0
          - 3.250 -> 90.0
          - 3.388 -> 100.0
          - 3.500 -> 100.0
      - clamp:
          min_value: 0
          max_value: 100
