esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control DYI smart battery"
  includes:
    - "${device_name}/helpers"
  project:
    name: "syssi.esphome-jbd-bms"
    version: 1.5.0

packages:
  battery: !include {
    file: modules/battery.yaml
  }
  display: !include {
    file: modules/display.yaml
  }
  debug: !include modules/debug.yaml

external_components:
  - source: github://syssi/esphome-jbd-bms
    refresh: 7d

logger:
  baud_rate: 0

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
#  frequency: 100kHz
  scan: false

switch:
  - platform: gpio
    name: "Balancer Switch"
    pin:
      number: ${balancer_switch_pin}
      inverted: false
      drive_strength: 20mA
      mode:
        output: true
        pullup: true

sensor:
  - platform: htu21d
    temperature:
      name: "Box Temperature"
    humidity:
      name: "Box Humidity"
    update_interval: 10s
