esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control DYI smart battery"
  includes:
    - "${device_name}/helpers"
  project:
    name: "odya.esphome-smart-battery"
    version: 1.6.3

packages:
  bms: !include {
    file: modules/bms.yaml
  }
  balancer: !include {
    file: modules/balancer.yaml
  }
  display: !include {
    file: modules/display.yaml
  }
  deep_sleep: !include {
    file: modules/deep_sleep.yaml
  }
  debug: !include modules/debug.yaml

external_components:
  - source: github://syssi/esphome-jbd-bms
    refresh: 7d

logger:
  baud_rate: 0

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
#  frequency: 100kHz
  scan: false

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: htu21d
    temperature:
      name: "Box Temperature"
    humidity:
      name: "Box Humidity"
    update_interval: ${sensors_update_interval}

  - platform: internal_temperature
    name: "Controller Temperature"
    update_interval: ${sensors_update_interval}
